version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps container port 3000 to host port 3000
    environment:
      - NODE_ENV=production # Ensures the application runs in production mode
    volumes:
      - .:/app # Optional: Mount local code for development
      - /app/node_modules # Ensures node_modules are managed in the container